### PR TITLE
3D Texture-based Direct Volume Rendering

### PR DESCRIPTION
**Pull request by senften**
This PR is based on [3D Texture + Example by senften · Pull Request #20 · seanspicer/nexscenegraph](https://github.com/seanspicer/nexscenegraph/pull/20) 

Introduced a delegate to LevoyCabralTechnique which is responsible for converting an IVoxelVolume into an RGBA Texture3D. The technique now creates and owns the ITexture3D accessing the data of the IVoxelVolume and using the delegate to translate into color, basically.

Also pay attention to the TexGen in LevoyCabralLocator and the example TextureVolumeShader-fragment.glsl.

### CODE REVIEW

**Review by seanspicer — CHANGES_REQUESTED** [review]
So, as you suggest - I really prefer that the 3D Texture generation happen inside the Init method for the LevoyCabralTechnique.   This is actually a small change I think.

Other than that the rest looks reasonable.

**Comment by senften** [comment]
> So, as you suggest - I really prefer that the 3D Texture generation happen inside the Init method for the LevoyCabralTechnique. This is actually a small change I think.
> 
> Other than that the rest looks reasonable.

Agreed.

**Review by seanspicer — CHANGES_REQUESTED** [review]
So, I agree with the use of the delegate, but I think there needs to be a default delegate if the user does not provide one.   I don't think the caller of the API should need to know (at all) about how to create the texture data.  I'd provide a constructor with a default ITextureTranslator implementation so the user has the option (but not the requirement) to override it.

**Comment by senften** [comment]
Add a default delegate. I had an explicit parula colormap implementation but I thought it was just too lengthy so I repurposed a procedural map. It's not an unreasonable default but I think someone would overwrite it pretty quickly.

**Pull request merged**
